[versions]
kotlin = "2.0.21"
shadow = "9.0.0-beta11"
paperweight = "2.0.0-beta.16"
paper = "1.21.4-R0.1-SNAPSHOT"
runpaper = "2.3.1"
mcchestuiplus = "1.5.6"
bstats = "3.0.2"
reflections = "0.10.2"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runpaper" }

[libraries]
mcchestuiplus = { module = "com.github.DebitCardz:mc-chestui-plus", version.ref = "mcchestuiplus" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
reflections = { module = "org.reflections:reflections", version.ref = "reflections" }